// ============================================================
// AUV Feature Normalization Parameters (Min-Max, 0~1)
// Auto-generated by step8_quantize_tinyml.py
// Usage: norm = (raw_val - FEAT_MINS[i]) / FEAT_RANGES[i]
//        clamp to [0.0, 1.0] before inference
// ============================================================
#ifndef AUV_NORM_PARAMS_H
#define AUV_NORM_PARAMS_H

#define NUM_FEATURES 30

// 각 특징의 최솟값 (정규화 공식의 분자 보정)
const float FEAT_MINS[NUM_FEATURES] = {
  -7.02812500f,  // [00] pH_mean
  0.00551100f,  // [01] pH_std
  -1.10627381f,  // [02] pH_slope
  1.67934744f,  // [03] pH_rms
  -4104.33906250f,  // [04] EC_mean
  0.49400458f,  // [05] EC_std
  -271.29727106f,  // [06] EC_slope
  232.15180580f,  // [07] EC_rms
  1.77187500f,  // [08] DO_mean
  0.10540797f,  // [09] DO_std
  -3.14130266f,  // [10] DO_slope
  2.17291567f,  // [11] DO_rms
  0.00000000f,  // [12] O2_mean
  0.00000000f,  // [13] O2_std
  0.00000000f,  // [14] O2_slope
  0.00000000f,  // [15] O2_rms
  0.00000000f,  // [16] depth_mean
  0.00000000f,  // [17] depth_std
  0.00000000f,  // [18] depth_slope
  2.56531250f,  // [19] temp_mean
  0.01771905f,  // [20] temp_std
  -1.24672230f,  // [21] temp_slope
  0.00000000f,  // [22] imu_mean
  0.00000000f,  // [23] imu_std
  0.00000000f,  // [24] imu_max
  -0.99937176f,  // [25] pH_temp_corr
  -13.34723750f,  // [26] pH_res_mean
  0.00528334f,  // [27] pH_res_std
  -7.78761875f,  // [28] DO_res_mean
  0.10724000f  // [29] DO_res_std
};

// 각 특징의 범위값 (정규화 분모: max - min)
const float FEAT_RANGES[NUM_FEATURES] = {
  62.35843750f,  // [00] pH_mean
  44.06325547f,  // [01] pH_std
  2.32166323f,  // [02] pH_slope
  66.80459915f,  // [03] pH_rms
  7865.35781250f,  // [04] EC_mean
  25424.56465224f,  // [05] EC_std
  559.23527015f,  // [06] EC_slope
  25397.58229456f,  // [07] EC_rms
  146.02500000f,  // [08] DO_mean
  71.81479315f,  // [09] DO_std
  6.25848672f,  // [10] DO_slope
  145.62529241f,  // [11] DO_rms
  1.00000000f,  // [12] O2_mean
  1.00000000f,  // [13] O2_std
  1.00000000f,  // [14] O2_slope
  1.00000000f,  // [15] O2_rms
  1.00000000f,  // [16] depth_mean
  1.00000000f,  // [17] depth_std
  1.00000000f,  // [18] depth_slope
  59.51312500f,  // [19] temp_mean
  47.72019800f,  // [20] temp_std
  2.12176534f,  // [21] temp_slope
  1.00000000f,  // [22] imu_mean
  1.00000000f,  // [23] imu_std
  1.00000000f,  // [24] imu_max
  1.99931987f,  // [25] pH_temp_corr
  61.50699375f,  // [26] pH_res_mean
  43.91537933f,  // [27] pH_res_std
  143.15191875f,  // [28] DO_res_mean
  71.82744727f  // [29] DO_res_std
};

#endif // AUV_NORM_PARAMS_H